# Markdown Lint Configuration for EPiC Infrastructure

# Default state for all rules
default: true

# MD003 - Header style
MD003:
  style: "atx"

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

# MD022 - Headers should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024 - Multiple headers with the same content
MD024:
  allow_different_nesting: true

# MD025 - Multiple top level headers in the same document
MD025:
  front_matter_title: ""

# MD026 - Trailing punctuation in header
MD026:
  punctuation: ".,;:!?"

# MD029 - Ordered list item prefix
MD029:
  style: "ordered"

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD033 - Allow inline HTML for specific tags
MD033:
  allowed_elements: ["br", "sub", "sup", "kbd", "details", "summary"]

# MD034 - Bare URL used
MD034: false

# MD036 - Emphasis used instead of a header
MD036:
  punctuation: ".,;:!?。，；：！？"

# MD040 - Fenced code blocks should have a language specified
MD040: true

# MD041 - First line in file should be a top level header
MD041: false

# MD046 - Code block style
MD046:
  style: "fenced"

# MD048 - Code fence style
MD048:
  style: "backtick"